### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by leovanhaaren** [pksunkara/vue-cli-plugin-storybook#3]
@almeynman you still actively developing the plugin? Would like to pick it up if you don't mind.

**Comment by almeynman** [comment]
@leovanhaaren Thanks! Please do. Currently have no time to work on it.

**Comment by pksunkara** [comment]
@almeynman Would you be willing to accept PRs, or should we start a new module?

**Comment by almeynman** [comment]
@pksunkara I am willing to accept PR. I am also willing to transfer ownership of this project if you are interested

**Comment by pksunkara** [comment]
I am willing to maintain this and improve this.

**Comment by pksunkara** [comment]
@almeynman Thanks for transferring the repo. I will be working on fixing the broken stuff this week. Could you also add me as owner on npm? https://www.npmjs.com/package/vue-cli-plugin-storybook

**Comment by almeynman** [comment]
@pksunkara I have added you as admin. When you confirm, I will remove myself

**Comment by pksunkara** [comment]
Confirmed. Thanks for everything.
