### ISSUE TITLE
Static assets are not copied

### ISSUE THREAD

**Issue by leovanhaaren** [pksunkara/vue-cli-plugin-storybook#4]
Hi,

Today i've noticed that with the latest version of this plugin, static assets from components are not copied to the static storybook folder.

Webpack is loading them like `<img src="img/ic-forward.f9f0c5c8.svg">` but within the `storybook-static` folder there are no images copied. This prob has to do with the new webpack config that was added in the latest release.

**Comment by leovanhaaren** [comment]
To clarify, this happens in dev mode. Building storybook seems to work fine.

**Comment by leovanhaaren** [comment]
```
This page contains the following errors:
error on line 1 at column 1: Document is empty

Below is a rendering of the page up to the first error.
```

**Comment by pksunkara** [comment]
@leovanhaaren I am working on releasing a new version (probably today). I am not sure whether this particular issue will be fixed or not. The new version will completely use your vue project's webpack config. If you are interested, we could chat on Vue discord #webpack channel once I publish the next version

**Comment by leovanhaaren** [comment]
Cool! I'll wait for the new version then, if the issue still persist we can indeed have a chat. Thanks for the fast reply!

**Comment by pksunkara** [comment]
@leovanhaaren 0.3.0 is released. It should be a completely good version (except for typescript and lint)

**Comment by leovanhaaren** [comment]
@pksunkara I can now confirm that it works. Thanks for the fast update!

**Comment by pksunkara** [comment]
@leovanhaaren Np. Don't mind to open issues for any thing you think is wrong.
